source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "jekyll-theme-cayman"
gem "jekyll-seo-tag"
gem "jekyll-relative-links"
gem "webrick", "~> 1.8"

group :jekyll_plugins do
  gem "jekyll-sitemap"
  gem "jekyll-feed"
end
